const DataItems = [
  // HEADERS
  {
    type: 'Headers',
    name: 'Victory Naruto Bandana',
    imagePath: 'imgs/item_imgs/10602.png',
    level: 600,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 10602,
  },
  {
    type: 'Headers',
    name: 'Otsutsuki Mask',
    imagePath: 'imgs/item_imgs/7759.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 7759,
  },
  {
    type: 'Headers',
    name: 'Kaguya Mask',
    imagePath: 'imgs/item_imgs/11337.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 11337,
  },
  {
    type: 'Headers',
    name: 'Ultimate Sennin Bandana ',
    imagePath: 'imgs/item_imgs/2456.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 2456,
  },
  {
    type: 'Headers',
    name: 'Ultimate Senju Protector',
    imagePath: 'imgs/item_imgs/2475.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 2475,
  },
  {
    type: 'Headers',
    name: 'Senju Protector',
    imagePath: 'imgs/item_imgs/2467.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 2467,
  },
  {
    type: 'Headers',
    name: 'Kurama Bandana',
    imagePath: 'imgs/item_imgs/11419.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 11419,
  },
  {
    type: 'Headers',
    name: 'Uchiha Bandana',
    imagePath: 'imgs/item_imgs/2466.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 2466,
  },
  {
    type: 'Headers',
    name: 'Obito Mask',
    imagePath: 'imgs/item_imgs/124.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 124,
  },
  {
    type: 'Headers',
    name: 'Hokage Hat',
    imagePath: 'imgs/item_imgs/126.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 126,
  },
  {
    type: 'Headers',
    name: 'Yamato Protector',
    imagePath: 'imgs/item_imgs/125.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 125,
  },
  {
    type: 'Headers',
    name: 'Jiraya Protector',
    imagePath: 'imgs/item_imgs/2647.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 2647,
  },
  {
    type: 'Headers',
    name: 'Strong Anbu Mask',
    imagePath: 'imgs/item_imgs/7455.gif',
    level: 550,
    atribute: 'Regen',
    description: 'Constado em',
    especial: '',
    idgame: 7455,
  },
  // Bodies =========================================================================================================
  {
    type: 'Bodies',
    name: 'Victory Naruto Armor',
    imagePath: 'imgs/item_imgs/10603.png',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 10603,
  },
  {
    type: 'Bodies',
    name: 'Otsutsuki Robe',
    imagePath: 'imgs/item_imgs/7760.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7760,
  },
  {
    type: 'Bodies',
    name: 'Royal Flame Coat',
    imagePath: 'imgs/item_imgs/11338.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11338,
  },
  {
    type: 'Bodies',
    name: 'Ultimate Sannin Coat',
    imagePath: 'imgs/item_imgs/2479.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2479,
  },
  {
    type: 'Bodies',
    name: 'Ultimate Senju Armor',
    imagePath: 'imgs/item_imgs/2476.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2476,
  },
  {
    type: 'Bodies',
    name: 'Senju Armor',
    imagePath: 'imgs/item_imgs/2463.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2463,
  },
  {
    type: 'Bodies',
    name: 'Kurama Tunic',
    imagePath: 'imgs/item_imgs/11420.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11420,
  },
  {
    type: 'Bodies',
    name: 'Uchiha Coat',
    imagePath: 'imgs/item_imgs/2462.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2462,
  },
  {
    type: 'Bodies',
    name: 'Yondaime Coat',
    imagePath: 'imgs/item_imgs/7463.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7463,
  },
  {
    type: 'Bodies',
    name: 'Madara Armor',
    imagePath: 'imgs/item_imgs/7453.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7453,
  },
  {
    type: 'Bodies',
    name: 'Hashirama Armor',
    imagePath: 'imgs/item_imgs/8854.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 8854,
  },
  {
    type: 'Bodies',
    name: 'Nidaime Armor',
    imagePath: 'imgs/item_imgs/7407.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7407,
  },
  {
    type: 'Bodies',
    name: 'Renegade Armor',
    imagePath: 'imgs/item_imgs/11476.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11476,
  },
  
  // Legs =========================================================================================================
  {
    type: 'Legs',
    name: 'Victory Naruto Legs',
    imagePath: 'imgs/item_imgs/10605.png',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 10605,
  },
  {
    type: 'Legs',
    name: 'Otsutsuki Legs',
    imagePath: 'imgs/item_imgs/7761.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7761,
  },
  {
    type: 'Legs',
    name: 'Uchiha Kilt',
    imagePath: 'imgs/item_imgs/11319.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11319,
  },
  {
    type: 'Legs',
    name: 'Ultimate Sannin Legs',
    imagePath: 'imgs/item_imgs/2473.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2473,
  },
  {
    type: 'Legs',
    name: 'Ultimate Senju Legs',
    imagePath: 'imgs/item_imgs/2477.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2477,
  },
  {
    type: 'Legs',
    name: 'Senju Legs',
    imagePath: 'imgs/item_imgs/2465.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2465,
  },
  {
    type: 'Legs',
    name: 'Kurama Legs',
    imagePath: 'imgs/item_imgs/11421.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11421,
  },
  {
    type: 'Legs',
    name: 'Uchiha Legs',
    imagePath: 'imgs/item_imgs/2464.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2464,
  },
  {
    type: 'Legs',
    name: 'Sennin Legs',
    imagePath: 'imgs/item_imgs/11475.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11475,
  },
  {
    type: 'Legs',
    name: 'Madara Legs',
    imagePath: 'imgs/item_imgs/2429.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2429,
  },
  {
    type: 'Legs',
    name: 'Hashirama Legs',
    imagePath: 'imgs/item_imgs/2452.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2452,
  },
  {
    type: 'Legs',
    name: 'Kakashi Legs',
    imagePath: 'imgs/item_imgs/7454.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7454,
  },
  {
    type: 'Legs',
    name: 'Sasuke Legs',
    imagePath: 'imgs/item_imgs/150.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 150,
  },
  // Feet =========================================================================================================
  {
    type: 'Feet',
    name: 'Victory Naruto Boots',
    imagePath: 'imgs/item_imgs/10606.png',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 10606,
  },
  {
    type: 'Feet',
    name: 'Otsutsuki Boots',
    imagePath: 'imgs/item_imgs/7762.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7762,
  },
  {
    type: 'Feet',
    name: 'Royal Uchiha Boots',
    imagePath: 'imgs/item_imgs/11321.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11321,
  },
  {
    type: 'Feet',
    name: 'Ultimate Sannin Boots',
    imagePath: 'imgs/item_imgs/2474.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2474,
  },
  {
    type: 'Feet',
    name: 'Ultimate Senju Boots',
    imagePath: 'imgs/item_imgs/2478.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2478,
  },
  {
    type: 'Feet',
    name: 'Senju Boots',
    imagePath: 'imgs/item_imgs/2470.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2470,
  },
  {
    type: 'Feet',
    name: 'Kurama Boots',
    imagePath: 'imgs/item_imgs/11422.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11422,
  },
  {
    type: 'Feet',
    name: 'Uchiha Boots',
    imagePath: 'imgs/item_imgs/2468.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2468,
  },
  {
    type: 'Feet',
    name: 'Vital Boots',
    imagePath: 'imgs/item_imgs/123.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 123,
  },
  {
    type: 'Feet',
    name: 'Madara Boots',
    imagePath: 'imgs/item_imgs/2161.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2161,
  },
  {
    type: 'Feet',
    name: 'Silence Boots',
    imagePath: 'imgs/item_imgs/146.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 146,
  },
  {
    type: 'Feet',
    name: 'Chunin Boots',
    imagePath: 'imgs/item_imgs/122.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 122,
  },
  {
    type: 'Feet',
    name: 'Jiraya Sandal',
    imagePath: 'imgs/item_imgs/7456.gif',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7456,
  },
  // Amulets =========================================================================================================

  // Rings =========================================================================================================
  
  // Weapons =========================================================================================================
 
  // Shields =========================================================================================================
  
  // Backpacks =========================================================================================================
  
  // Especial =========================================================================================================
  
];
 
export default DataItems;

