const DataItems = [
  // HEADERS
  {
    type: 'Headers',
    name: 'Victory Naruto Bandana',
    imagePath: 'imgs/item_imgs/10602.gif',
    imageDetail: 'Victory Naruto',
    level: 600,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em [BOSS] Victory Naruto',
    especial: '',
    idgame: 10602,
  },
  {
    type: 'Headers',
    name: 'Otsutsuki Mask',
    imagePath: 'imgs/item_imgs/7759.gif',
    imageDetail: 'Hagoromo',
    level: 550,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em [BOSS] Victory Naruto',
    especial: '',
    idgame: 7759,
  },
  {
    type: 'Headers',
    name: 'Obito Mask',
    imagePath: 'imgs/item_imgs/11337.gif',
    imageDetail: 'Obito',
    level: 500,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em ',
    especial: '',
    idgame: 11337,
  },
  {
    type: 'Headers',
    name: 'Ultimate Sennin Bandana ',
    imagePath: 'imgs/item_imgs/2456.gif',
    imageDetail: 'maintence',
    level: 400,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em ',
    especial: '',
    idgame: 2456,
  },
  {
    type: 'Headers',
    name: 'Raikage Bandana',
    imagePath: 'imgs/item_imgs/2475.gif',
    imageDetail: 'Raikage',
    level: 450,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em ',
    especial: '',
    idgame: 2475,
  },
  {
    type: 'Headers',
    name: 'Supreme Uchiha Hood',
    imagePath: 'imgs/item_imgs/2467.gif',
    imageDetail: 'vip',
    level: 0,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item pode ser comprado na Loja VIP.',
    especial: '',
    idgame: 2467,
  },
  {
    type: 'Headers',
    name: 'Kurama Bandana',
    imagePath: 'imgs/item_imgs/11419.gif',
    imageDetail: 'Kyuubi',
    level: 400,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em ',
    especial: '',
    idgame: 11419,
  },
  {
    type: 'Headers',
    name: 'Uchiha Bandana',
    imagePath: 'imgs/item_imgs/2466.gif',
    imageDetail: 'Shisui',
    level: 350,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'x.x% Drop Chance em ',
    especial: '',
    idgame: 2466,
  },
  {
    type: 'Headers',
    name: 'Sage Protector',
    imagePath: 'imgs/item_imgs/124.gif',
    imageDetail: 'quest5',
    level: 300,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 124,
  },
  {
    type: 'Headers',
    name: 'Hokage Hat',
    imagePath: 'imgs/item_imgs/126.gif',
    imageDetail: 'quest4',
    level: 200,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 126,
  },
  {
    type: 'Headers',
    name: 'Yamato Protector',
    imagePath: 'imgs/item_imgs/125.gif',
    imageDetail: 'quest3',
    level: 150,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 125,
  },
  {
    type: 'Headers',
    name: 'Jiraya Protector',
    imagePath: 'imgs/item_imgs/2647.gif',
    imageDetail: 'quest2',
    level: 100,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 2647,
  },
  {
    type: 'Headers',
    name: 'Strong Anbu Mask',
    imagePath: 'imgs/item_imgs/7455.gif',
    imageDetail: 'quest1',
    level: 50,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 7455,
  },
  // Bodies =========================================================================================================
  {
    type: 'Bodies',
    name: 'Victory Naruto Armor',
    imagePath: 'imgs/item_imgs/10603.gif',
    imageDetail: 'Victory Naruto',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 10603,
  },
  {
    type: 'Bodies',
    name: 'Otsutsuki Robe',
    imagePath: 'imgs/item_imgs/7760.gif',
    imageDetail: 'Hagoromo',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 7760,
  },
  {
    type: 'Bodies',
    name: 'Obito Robe',
    imagePath: 'imgs/item_imgs/11338.gif',
    imageDetail: 'Obito',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 11338,
  },
  {
    type: 'Bodies',
    name: 'Ultimate Sannin Coat',
    imagePath: 'imgs/item_imgs/2479.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2479,
  },
  {
    type: 'Bodies',
    name: 'Raikage coat',
    imagePath: 'imgs/item_imgs/2476.gif',
    imageDetail: 'Raikage',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2476,
  },
  {
    type: 'Bodies',
    name: 'Supreme Uchiha Cape',
    imagePath: 'imgs/item_imgs/2463.gif',
    imageDetail: 'vip',
    level: 0,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item pode ser comprado na Loja VIP.',
    especial: '',
    idgame: 2463,
  },
  {
    type: 'Bodies',
    name: 'Kurama Tunic',
    imagePath: 'imgs/item_imgs/11420.gif',
    imageDetail: 'Kyuubi',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 11420,
  },
  {
    type: 'Bodies',
    name: 'Uchiha Coat',
    imagePath: 'imgs/item_imgs/2462.gif',
    imageDetail: 'Shisui',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2462,
  },
  {
    type: 'Bodies',
    name: 'Yondaime Coat',
    imagePath: 'imgs/item_imgs/7463.gif',
    imageDetail: 'quest5',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 7463,
  },
  {
    type: 'Bodies',
    name: 'Madara Armor',
    imagePath: 'imgs/item_imgs/7453.gif',
    imageDetail: 'quest4',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 7453,
  },
  {
    type: 'Bodies',
    name: 'Hashirama Armor',
    imagePath: 'imgs/item_imgs/8854.gif',
    imageDetail: 'quest3',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 8854,
  },
  {
    type: 'Bodies',
    name: 'Nidaime Armor',
    imagePath: 'imgs/item_imgs/7407.gif',
    imageDetail: 'quest2',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 7407,
  },
  {
    type: 'Bodies',
    name: 'Renegade Armor',
    imagePath: 'imgs/item_imgs/11476.gif',
    imageDetail: 'quest1',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 11476,
  },
  
  // Legs =========================================================================================================
  {
    type: 'Legs',
    name: 'Victory Naruto Legs',
    imagePath: 'imgs/item_imgs/10605.gif',
    imageDetail: 'Victory Naruto',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 10605,
  },
  {
    type: 'Legs',
    name: 'Otsutsuki Legs',
    imagePath: 'imgs/item_imgs/7761.gif',
    imageDetail: 'Hagoromo',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 7761,
  },
  {
    type: 'Legs',
    name: 'Obito Kilt',
    imagePath: 'imgs/item_imgs/11319.gif',
    imageDetail: 'Obito',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 11319,
  },
  {
    type: 'Legs',
    name: 'Ultimate Sannin Legs',
    imagePath: 'imgs/item_imgs/2473.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2473,
  },
  {
    type: 'Legs',
    name: 'Raikage Legs',
    imagePath: 'imgs/item_imgs/2477.gif',
    imageDetail: 'Raikage',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2477,
  },
  {
    type: 'Legs',
    name: 'Supreme Uchiha Legs',
    imagePath: 'imgs/item_imgs/2465.gif',
    imageDetail: 'vip',
    level: 0,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item pode ser comprado na Loja VIP.',
    especial: '',
    idgame: 2465,
  },
  {
    type: 'Legs',
    name: 'Kurama Legs',
    imagePath: 'imgs/item_imgs/11421.gif',
    imageDetail: 'Kyuubi',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 11421,
  },
  {
    type: 'Legs',
    name: 'Uchiha Legs',
    imagePath: 'imgs/item_imgs/2464.gif',
    imageDetail: 'Shisui',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2464,
  },
  {
    type: 'Legs',
    name: 'Sennin Legs',
    imagePath: 'imgs/item_imgs/11475.gif',
    imageDetail: 'quest5',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 11475,
  },
  {
    type: 'Legs',
    name: 'Madara Legs',
    imagePath: 'imgs/item_imgs/2429.gif',
    imageDetail: 'quest4',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 2429,
  },
  {
    type: 'Legs',
    name: 'Hashirama Legs',
    imagePath: 'imgs/item_imgs/2452.gif',
    imageDetail: 'quest3',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 2452,
  },
  {
    type: 'Legs',
    name: 'Kakashi Legs',
    imagePath: 'imgs/item_imgs/7454.gif',
    imageDetail: 'quest2',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 7454,
  },
  {
    type: 'Legs',
    name: 'Sasuke Legs',
    imagePath: 'imgs/item_imgs/150.gif',
    imageDetail: 'quest1',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 150,
  },
  // Feet =========================================================================================================
  {
    type: 'Feet',
    name: 'Victory Naruto Boots',
    imagePath: 'imgs/item_imgs/10606.gif',
    imageDetail: 'Victory Naruto',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 10606,
  },
  {
    type: 'Feet',
    name: 'Otsutsuki Boots',
    imagePath: 'imgs/item_imgs/7762.gif',
    imageDetail: 'Hagoromo',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 7762,
  },
  {
    type: 'Feet',
    name: 'Royal Uchiha Boots',
    imagePath: 'imgs/item_imgs/11321.gif',
    imageDetail: 'Obito',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 11321,
  },
  {
    type: 'Feet',
    name: 'Ultimate Sannin Boots',
    imagePath: 'imgs/item_imgs/2474.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2474,
  },
  {
    type: 'Feet',
    name: 'Raikage Boots',
    imagePath: 'imgs/item_imgs/2478.gif',
    imageDetail: 'imgs/item_details/10602.png',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2478,
  },
  {
    type: 'Feet',
    name: 'Supreme Uchiha Boots',
    imagePath: 'imgs/item_imgs/2470.gif',
    imageDetail: 'vip',
    level: 0,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item pode ser comprado na Loja VIP.',
    especial: '',
    idgame: 2470,
  },
  {
    type: 'Feet',
    name: 'Kurama Boots',
    imagePath: 'imgs/item_imgs/11422.gif',
    imageDetail: 'Kyuubi',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 11422,
  },
  {
    type: 'Feet',
    name: 'Uchiha Boots',
    imagePath: 'imgs/item_imgs/2468.gif',
    imageDetail: 'Shisui',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: '',
    especial: '',
    idgame: 2468,
  },
  {
    type: 'Feet',
    name: 'Vital Boots',
    imagePath: 'imgs/item_imgs/123.gif',
    imageDetail: 'quest5',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 123,
  },
  {
    type: 'Feet',
    name: 'Madara Boots',
    imagePath: 'imgs/item_imgs/2161.gif',
    imageDetail: 'quest4',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 2161,
  },
  {
    type: 'Feet',
    name: 'Silence Boots',
    imagePath: 'imgs/item_imgs/146.gif',
    imageDetail: 'quest3',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 146,
  },
  {
    type: 'Feet',
    name: 'Chunin Boots',
    imagePath: 'imgs/item_imgs/122.gif',
    imageDetail: 'quest2',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 122,
  },
  {
    type: 'Feet',
    name: 'Jiraya Sandal',
    imagePath: 'imgs/item_imgs/7456.gif',
    imageDetail: 'quest1',
    level: 1,
    atribute: 'Regeneração de Vida e Chakra em X p/s',
    description: 'Este item é recompensa de Quest !',
    especial: '',
    idgame: 7456,
  },
  // Amulets =========================================================================================================

  // Rings =========================================================================================================
  
  // Weapons =========================================================================================================
 {
    type: 'Weapons',
    name: 'Susano Sword',
    imagePath: 'imgs/item_imgs/8927.gif',
    imageDetail: 'Indra',
    level: 600,
    atribute: '',
    description: '',
    especial: '',
    idgame: 8927,
  },
 {
    type: 'Weapons',
    name: 'Kurama Sword',
    imagePath: 'imgs/item_imgs/11331.gif',
    imageDetail: 'Kyuubi',
    level: 600,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11331,
  },
 {
    type: 'Weapons',
    name: 'Izanami Glove',
    imagePath: 'imgs/item_imgs/11330.gif',
    imageDetail: 'Itachi',
    level: 600,
    atribute: '',
    description: '',
    especial: '',
    idgame: 8927,
  },
 {
    type: 'Weapons',
    name: 'Barisuta',
    imagePath: 'imgs/item_imgs/11332.gif',
    imageDetail: 'Sasuke The Last',
    level: 600,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11332,
  },
 {
    type: 'Weapons',
    name: 'Cetre Rikkudo',
    imagePath: 'imgs/item_imgs/11434.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11434,
  },
 {
    type: 'Weapons',
    name: 'Kage Shuriken',
    imagePath: 'imgs/item_imgs/2168.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2168,
  },
 {
    type: 'Weapons',
    name: 'Black Shuriken',
    imagePath: 'imgs/item_imgs/3964.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 3964,
  },
 {
    type: 'Weapons',
    name: 'Big Shuriken',
    imagePath: 'imgs/item_imgs/2399.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2399,
  },
 {
    type: 'Weapons',
    name: 'Dark Shuriken',
    imagePath: 'imgs/item_imgs/3965.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 3965,
  },
 {
    type: 'Weapons',
    name: 'Shukaku Spear',
    imagePath: 'imgs/item_imgs/7862.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7862,
  },
 {
    type: 'Weapons',
    name: 'Blood Sickle',
    imagePath: 'imgs/item_imgs/136.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 136,
  },
 {
    type: 'Weapons',
    name: 'Leque Dobradisso',
    imagePath: 'imgs/item_imgs/135.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 135,
  },
  {
    type: 'Weapons',
    name: 'Slayer Glove',
    imagePath: 'imgs/item_imgs/2376.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2376,
  },
  {
    type: 'Weapons',
    name: 'Dragon Glove',
    imagePath: 'imgs/item_imgs/134.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 134,
  },
  {
    type: 'Weapons',
    name: 'Raikage Glove',
    imagePath: 'imgs/item_imgs/2516.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2516,
  },
  {
    type: 'Weapons',
    name: 'Obscure Glove',
    imagePath: 'imgs/item_imgs/133.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 133,
  },
  {
    type: 'Weapons',
    name: 'Master Claws',
    imagePath: 'imgs/item_imgs/2644.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2644,
  },
  {
    type: 'Weapons',
    name: 'Blood Glove',
    imagePath: 'imgs/item_imgs/2649.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2649,
  },
  {
    type: 'Weapons',
    name: 'Sound Glove',
    imagePath: 'imgs/item_imgs/2383.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2383,
  },
  {
    type: 'Weapons',
    name: 'Plate Glove',
    imagePath: 'imgs/item_imgs/2645.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2645,
  },
  {
    type: 'Weapons',
    name: 'Shibuki Sword',
    imagePath: 'imgs/item_imgs/11424.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11424,
  },
  {
    type: 'Weapons',
    name: 'Samehada Sword',
    imagePath: 'imgs/item_imgs/2413.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2413,
  },
  {
    type: 'Weapons',
    name: 'Zabuza Sword',
    imagePath: 'imgs/item_imgs/7869.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 7869,
  },
  {
    type: 'Weapons',
    name: 'Flame Sword',
    imagePath: 'imgs/item_imgs/2440.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2440,
  },
  {
    type: 'Weapons',
    name: 'Faraoh Sword',
    imagePath: 'imgs/item_imgs/2442.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2442,
  },
  {
    type: 'Weapons',
    name: 'Ultimate Chakra Sword',
    imagePath: 'imgs/item_imgs/2438.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2438,
  },
  {
    type: 'Weapons',
    name: 'Esmerald Sword',
    imagePath: 'imgs/item_imgs/2441.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 2441,
  },
  {
    type: 'Weapons',
    name: 'Dual Katana Eletric',
    imagePath: 'imgs/item_imgs/132.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 132,
  },
  {
    type: 'Weapons',
    name: 'Cutting Dagger',
    imagePath: 'imgs/item_imgs/131.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 131,
  },

  // Shields =========================================================================================================
  {
    type: 'Shields',
    name: 'Naruto Victory Shield',
    imagePath: 'imgs/item_imgs/11229.gif',
    imageDetail: 'Naruto Victory',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11229,
  },
  
  {
    type: 'Shields',
    name: 'Gunbai',
    imagePath: 'imgs/item_imgs/11425.gif',
    imageDetail: 'Old Madara',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 11425,
  },
  {
    type: 'Shields',
    name: 'Juubi Shield',
    imagePath: 'imgs/item_imgs/11430.gif',
    imageDetail: 'vip',
    level: 1,
    atribute: '',
    description: 'Este item pode ser comprado na Loja VIP.',
    especial: '',
    idgame: 11430,
  },
  {
    type: 'Shields',
    name: 'Katon Snake Shield',
    imagePath: 'imgs/item_imgs/139.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 139,
  },
  {
    type: 'Shields',
    name: 'Raiton Snake Shield',
    imagePath: 'imgs/item_imgs/148.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 148,
  },
  {
    type: 'Shields',
    name: 'Suiton Snake Shield',
    imagePath: 'imgs/item_imgs/149.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 149,
  },
  {
    type: 'Shields',
    name: 'Fuuton Snake Shield',
    imagePath: 'imgs/item_imgs/138.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 138,
  },
  {
    type: 'Shields',
    name: 'Doton Snake Shield',
    imagePath: 'imgs/item_imgs/138.gif',
    imageDetail: 'maintence',
    level: 1,
    atribute: '',
    description: '',
    especial: '',
    idgame: 137,
  },
  // Backpacks =========================================================================================================
  
  // Especial =========================================================================================================
  
];
 
export default DataItems;

