const DataPersonagens = [
  {
    id: 1,
    name: 'Naruto',
    imagePath: 'imgs/perso_imgs/naruto.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 2,
    name: 'Sasuke',
    imagePath: 'imgs/perso_imgs/sasuke.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 3,
    name: 'Sakura',
    imagePath: 'imgs/perso_imgs/sakura.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 4,
    name: 'Kiba',
    imagePath: 'imgs/perso_imgs/kiba.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 5,
  //   name: 'Shino',
  //   imagePath: 'imgs/perso_imgs/shino.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 6,
  //   name: 'Hinata',
  //   imagePath: 'imgs/perso_imgs/hinata.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 7,
  //   name: 'Sai',
  //   imagePath: 'imgs/perso_imgs/sai.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 8,
    name: 'Shikamaru',
    imagePath: 'imgs/perso_imgs/shikamaru.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 9,
    name: 'Chouji',
    imagePath: 'imgs/perso_imgs/chouji.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 10,
  //   name: 'Ino',
  //   imagePath: 'imgs/perso_imgs/ino.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 11,
    name: 'Lee',
    imagePath: 'imgs/perso_imgs/lee.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 12,
    name: 'Neji',
    imagePath: 'imgs/perso_imgs/neji.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 13,
    name: 'Tenten',
    imagePath: 'imgs/perso_imgs/tenten.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 14,
  //   name: 'Killer Bee',
  //   imagePath: 'imgs/perso_imgs/bee.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 15,
    name: 'Gaara',
    imagePath: 'imgs/perso_imgs/gaara.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 16,
  //   name: 'Kankuro',
  //   imagePath: 'imgs/perso_imgs/kankuro.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 17,
    name: 'Temari',
    imagePath: 'imgs/perso_imgs/temari.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 18,
  //   name: 'Orochimaru',
  //   imagePath: 'imgs/perso_imgs/orochimaru.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 19,
  //   name: 'Jiraya',
  //   imagePath: 'imgs/perso_imgs/jiraya.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 20,
    name: 'Tsunade',
    imagePath: 'imgs/perso_imgs/tsunade.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 21,
  //   name: 'Menma',
  //   imagePath: 'imgs/perso_imgs/menma.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 22,
  //   name: 'Guy',
  //   imagePath: 'imgs/perso_imgs/guy.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 23,
    name: 'Kakashi',
    imagePath: 'imgs/perso_imgs/kakashi.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 24,
  //   name: 'Yamato',
  //   imagePath: 'imgs/perso_imgs/yamato.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 25,
    name: 'Hashirama',
    imagePath: 'imgs/perso_imgs/hashirama.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 26,
    name: 'Nidaime',
    imagePath: 'imgs/perso_imgs/nidaime.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 27,
    name: 'Sarutobi',
    imagePath: 'imgs/perso_imgs/sarutobi.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 28,
    name: 'Minato',
    imagePath: 'imgs/perso_imgs/minato.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 29,
  //   name: 'Raikage',
  //   imagePath: 'imgs/perso_imgs/raikage.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 30,
  //   name: 'Tsuchikage',
  //   imagePath: 'imgs/perso_imgs/tsuchikage.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 31,
  //   name: 'Deidara',
  //   imagePath: 'imgs/perso_imgs/deidara.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 32,
  //   name: 'Sasori',
  //   imagePath: 'imgs/perso_imgs/sasori.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 33,
    name: 'Kisame',
    imagePath: 'imgs/perso_imgs/kisame.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 34,
  //   name: 'Hidan',
  //   imagePath: 'imgs/perso_imgs/hidan.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 35,
  //   name: 'Kakuzo',
  //   imagePath: 'imgs/perso_imgs/kakuzo.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 36,
  //   name: 'Nagato',
  //   imagePath: 'imgs/perso_imgs/nagato.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 37,
  //   name: 'Shisui',
  //   imagePath: 'imgs/perso_imgs/shisui.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 38,
  //   name: 'Itachi',
  //   imagePath: 'imgs/perso_imgs/itachi.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  // {
  //   id: 39,
  //   name: 'Kabuto',
  //   imagePath: 'imgs/perso_imgs/kabuto.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
  {
    id: 40,
    name: 'Obito',
    imagePath: 'imgs/perso_imgs/obito.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  {
    id: 41,
    name: 'Madara',
    imagePath: 'imgs/perso_imgs/madara.png',
    linkVideo: 'www.youtube.com/LINK-VIDEO',
  },
  // {
  //   id: 42,
  //   name: 'Suigetsu',
  //   imagePath: 'imgs/perso_imgs/suigetsu.png',
  //   linkVideo: 'www.youtube.com/LINK-VIDEO',
  // },
];

export default DataPersonagens;
